version: "3"
services:
  google-traffic-screen:
    image: alatas/google-traffic-screen:latest
    environment:
      - all_proxy= #set proxy
    ports:
      - "8901:8901"
    volumes:
      - ./www/index.html:/www/index.html
      - ./settings.yml:/settings.yml
      - ./locations.yml:/locations.yml
    restart: always